from dataclasses import dataclass

@dataclass
class Packet():
    srcip: str
    sport: int
    dstip: str
    dsport: int
    proto: str
    state: str
    dur: float
    sbytes: int
    dbytes: int
    sttl: int
    dttl: int
    sloss: int
    dloss: int
    service: str
    Sload: float
    Dload: float
    Spkts: int
    Dpkts: int
    swin: int
    dwin: int
    stcpb: int
    dtcpb: int
    smeansz: int
    dmeansz: int
    trans_depth: int
    res_bdy_len: int
    Sjit: float
    Djit: float
    Stime: int
    Ltime: int
    Sintpkt: float
    Dintpkt: float
    tcprtt: float
    synack: float
    ackdat: float
    is_sm_ips_ports: bool
    ct_state_ttl: int
    ct_flw_http_mthd: int
    is_ftp_login: int
    ct_ftp_cmd: int
    ct_srv_src: int
    ct_srv_dst: int
    ct_dst_ltm: int
    ct_src_ltm: int
    ct_src_dport_ltm: int
    ct_dst_sport_ltm: int
    ct_dst_src_ltm: int
    attack_cat: str
    Label: bool
